name: 2023-fatiando-igeba
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.9
  - livereload==2.6.3
  - jupyter
  - jupyter-lab
  - numpy==1.22.*
  - matplotlib==3.7.*
  - pandas==2.0.*
  - pyproj==3.3.*
  - pygmt==0.8.0
  - boule==0.4.*
  - harmonica==0.6.*
  - ensaio==0.5.*
  - verde==1.7.*
  - pyvista==0.38.*
